{% set name = "smac" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ebd21c71da845bd3f69726edcc50c9d2656852bd3e48d092389e5386f57c0df4

build:
  number: 0
  noarch: python
  entry_points:
    - smac = smac.smac_cli:cmd_line_call
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
  run:
    - configspace >=0.4.14,<0.5
    - dask-core
    - distributed
    - emcee >=3.0.0  # Needed for command line
    - joblib
    - numpy >=1.7.1
    - psutil
    - pynisher >=0.4.1
    - pyrfr >=0.8.0
    - python >=3.7
    - scikit-learn >=0.22.0
    - scipy >=1.7.0
    - __linux

test:
  imports:
    - smac
    - smac.configspace
  commands:
    - pip check
    - smac --help
  requires:
    - pip


about:
  home: https://www.automl.org/automated-algorithm-design/algorithm-configuration/smac/
  summary: Sequential Model-based Algorithm Configuration
  description: |
    SMAC is a tool for algorithm configuration to optimize the parameters of arbitrary
    algorithms across a set of instances. This also includes hyperparameter optimization
    of ML algorithms. The main core consists of Bayesian Optimization in combination
    with an aggressive racing mechanism to efficiently decide which of two configurations
    performs better.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  doc_url: https://automl.github.io/SMAC3/
  dev_url: https://github.com/automl/SMAC3

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
