{% set name = "smac" %}
{% set version = "2.1.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: af9d3bffd4d8d233ecc872a8c0f7c245043d41340a7790091165d363b2f7fe63

build:
  number: 1
  noarch: python
  entry_points:
    - smac = smac.smac_cli:cmd_line_call
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - configspace >=0.6.1
    - dask-core
    - dask-jobqueue
    - regex
    - numpy >=1.23.3
    - scipy >=1.9.2
    - psutil
    - pynisher >=1.0.0
    - ConfigSpace >=0.6.1
    - joblib
    - scikit-learn >=1.1.2
    - pyrfr >=0.9.0
    - dask
    - emcee >=3.0.0
    - python >={{ python_min }}
    - pyyaml
    - __linux

test:
  requires:
    - python {{ python_min }}
  imports:
    - smac


about:
  home: https://www.automl.org/automated-algorithm-design/algorithm-configuration/smac/
  summary: Sequential Model-based Algorithm Configuration
  description: |
    SMAC is a tool for algorithm configuration to optimize the parameters of arbitrary
    algorithms across a set of instances. This also includes hyperparameter optimization
    of ML algorithms. The main core consists of Bayesian Optimization in combination
    with an aggressive racing mechanism to efficiently decide which of two configurations
    performs better.
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  doc_url: https://automl.github.io/SMAC3/
  dev_url: https://github.com/automl/SMAC3

extra:
  recipe-maintainers:
    - BastianZim
    - mfeurer
